### PR TITLE
Add gzip compression to responses

### LINKED ISSUE #27: Enable Gzip support

### PR DESCRIPTION
**Pull request by rafalp**
### TODO

* [x] Add NGINX reverse proxy.
* [x] Replace `env` with `config`.
* [x] Generate config files when user sets vhost.
* [x] Gzip all responses.
* ~~Cache responses that don't send no-cache header, so we are not compressing static/media again and again and again.~~ not supported in nginx

Fixes #27

### CODE REVIEW

**Comment by rafalp** [comment]
@einarf can you give me a hand on this one? I'm like this 👌close of moving gzip to nginx because `UWSGI` documentation is completely barebones, and whatever I try, I get gzip working either for root path only, or nothing at all producing garbled responses like this one:

zrzut ekranu 2018-10-14 o 21 50 26

**Comment by rafalp** [comment]
I've looked this up on both UWSGI's mailing list and in the docs, and looks like its impossible to do on-the-fly gzip together with `static-map`, because as soon as pattern matches `static-map` clause, its short-circuited to UWSGI's static file serving machinery, so all `route-if` or `gzip` transforms have no effect on it.

NGINX it is.

**Comment by ly1989abc** [comment]
Hi, @rafalp 
I have a project that frontend built with vue.js and backend with built with django and drf and I build them with docker in production. I am planning to integrate your misgo as local forum, cause I'm very optimistic about it. In my project, I manage static files with nginx not django, So I just confused that why using django itself not nginx to manage static files, does it better? BTW, I'm finding a way to auth users with sso that I built with jwt not auth token. I am looking forward to your answers, thanks!

**Comment by rafalp** [comment]
@ly1989abc can you please ask your questions on support forums? https://misago-project.org/

**Pull request merged**
